### ISSUE TITLE
How can I create a class extended ts-eventemitter?

### ISSUE THREAD

**Issue by mizunashi-mana** [kimamula/ts-eventemitter#2]
Thanks awesome project.  This helped my understanding about typescript's type.

Anyway, I wanted such as:

```
interface MyEventEmitter {
  event(name: 'myevent'): Event1<MyEventEmitter, number>;
  event(name: string): EventBase<MyEventEmitter>;
}

class MyClass implements MyEventEmitter {
  public constructor(protected options : MyOptions){}
}

(new MyClass({ ... })).event('myevent').emit('myevent', 1);
```

But, this is miss.  Ok, I know, interface is unsubstantial.
I think I cannot do with ts-eventemitter.

However, there must are some situations creating a class extended this.
Actually, EventEmitter was extended some famous classes.

If you have a solution, would you tell me?

**Comment by kimamula** [comment]
Try this.

```
interface MyEventEmitter {
  event(name: 'myevent'): Event1<MyEventEmitter, number>;
  event(name: string): EventBase<MyEventEmitter>;
}

class MyClass implements MyEventEmitter {
  public constructor(protected options : MyOptions){}
  event = TsEventEmitter.create().event;
}
```

EDIT
Sorry, the above code is not correct.
Try this instead.

``` typescript
interface MyEventEmitter extends TsEventEmitter {
  event(name: 'myevent'): Event1<MyEventEmitter, number>;
  event(name: string): EventBase<MyEventEmitter>;
}

class MyClass implements MyEventEmitter {
  private eventEmitter = TsEventEmitter.create();
  public constructor(protected options : MyOptions){}
  event(name: string): any {
    return this.eventEmitter.event(name);
  }
  removeAllListeners(): void {
      this.eventEmitter.removeAllListeners();
  }
  setMaxListeners(n: number): void {
      this.eventEmitter.setMaxListeners(n);
  }
}
```

**Comment by mizunashi-mana** [comment]
I think that is not correct... Maybe, the type of `event` function is `(name: string): any`.
Actually, I get a solution.

```
class MyClass {
  private eventEmitter = TsEventEmitter.create();
  public constructor(protected options : MyOptions){}

  event(name: 'myevent'): Event1<MyClass, number>;
  event(name: string): EventBase<MyClass>;
  event(name: string): any {
    return this.eventEmitter.event(name);
  }
  removeAllListeners(): void {
      this.eventEmitter.removeAllListeners();
  }
  setMaxListeners(n: number): void {
      this.eventEmitter.setMaxListeners(n);
  }
}
```

However, I think that is not better way.
This class(`MyClass`) have same function to `TsEventEmitterImpl`.
And, I write helper class every time using `ts-eventemitter`.

I think the way is to export `TsEventEmitterImpl` class.
But, I have no confident.

**Comment by kimamula** [comment]
I didn't think of you always create your own class implementing `TsEventEmitter`.

Exporting `TsEventEmitterImpl` is not impossible, but I want to see how `EventEmitter` is generally inherited beforehand.
You mentioned there are some famous classes extending `EventEmitter`, right?
Please provide some examples.

Or, can't you adapt "composition over inheritance" principle?

**Comment by mizunashi-mana** [comment]
https://github.com/borisyankov/DefinitelyTyped/blob/2d4c4679bc2b509f27435a4f9da5e2de11258571/yeoman-generator/yeoman-generator.d.ts

using yeoman generator.

https://github.com/borisyankov/DefinitelyTyped/blob/27e02d6674ffe8186a567515b4c157bcf945911e/node/node.d.ts#L189

Most famous classes are in node module.
WritableStream class was extended EventEmitter class.
stream module, too.

And, some module including gulp and gulp plugins are extended Stream class.
Stream class extended EventEmitter, so I think to extend EventEmitter class is famous solution writing typescript on node.js.

**Comment by kimamula** [comment]
Thank you for providing information, I will take a look.

**Comment by kimamula** [comment]
Exporting `TsEventEmitterImpl` would disrupt the flexibility of the design.
You can define your own base class

``` typescript
class BaseClass implements TsEventEmitter {
  private eventEmitter = TsEventEmitter.create();
  event(name: string): EventBase<TsEventEmitter> {
    return this.eventEmitter.event(name);
  }
  removeAllListeners(): void {
      this.eventEmitter.removeAllListeners();
  }
  setMaxListeners(n: number): void {
      this.eventEmitter.setMaxListeners(n);
  }
}
```

and extend it anywhere you want to inherit TsEventEmitter.

``` typescript
interface MyEventEmitter extends TsEventEmitter {
  event(name: 'myevent'): Event1<MyEventEmitter, number>;
  event(name: string): EventBase<MyEventEmitter>;
}

class MyClass extends BaseClass implements MyEventEmitter {
  public constructor(protected options : MyOptions) {
      super();
  }
}
```

**Comment by mizunashi-mana** [comment]
I see.
Actually, I have been thinking you probably want to keep the flexibility of the design.
But, I have also been thinking the interface `TsEventEmitter` wasn't available until it is provided its content by class.

OK, I should follow your advice.  I decide to write base class on my projects.

However, if you get a great idea, tell me, please.  And, if you change your mind, I will be glad you think about this problem.
Thanks for discussing.
