### ISSUE TITLE
Cannot give useful name to generic event arguments

### ISSUE THREAD

**Issue by tyson-benson** [kimamula/ts-eventemitter#3]
Hi there,

Thanks for this project, it's good to see an effort towards strongly typed events. I have one issue though, and that is I cannot see a way to give useful names to the arguments of Event0..2.

Can you suggest how this might be accomplished without a lot of extra code? I like how terse the type definitions are in your example code.

Cheers

**Comment by kimamula** [comment]
I'm glad to know you like this project.

Probably a type alias is what you want.

``` typescript
type MyEvent = Event2<MyEventEmitter, number, string>;
interface MyEventEmitter extends TsEventEmitter {
    event(name: 'myEvent'): MyEvent;
    event(name: string): EventBase<MyEventEmitter>;
}
```

See the below link for detail.
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.10

EDIT:
I think I misunderstood your question.
You want to give names to the arguments of events, not to the events.

Unfortunately, I think there is no way to accomplish your requirement.
My advice is not to use Event2.
When you use Event0, you have no argument.
When you use Event1, I think generally it's not difficult to estimate what is required for the argument.
However, when you use Event2, it would be sometimes hard to understand what are exactly required.

Therefore, I recommend to define a interface and use it with Event1.

``` typescript
Interface Size {
    width: number;
    height: number;
}
interface MyEventEmitter extends TsEventEmitter {
    event(name: 'sizeChanged'): Event1<MyEventEmitter, Size>;
    event(name: string): EventBase<MyEventEmitter>;
}
```

And this is why I don't provide Event3, 4...
